### ISSUE TITLE
Release 0.3

### ISSUE THREAD

**Issue by edeustace** [justwrote/scala-faker#2]
Is it possible for you to create a release of 0.3? I don't like depending on SNAPSHOTS.

**Comment by benburton** [comment]
:+1:

**Comment by justwrote** [comment]
As of this writing, the latest stable version is 0.2 and is identical to 0.3-SNAPSHOT. I've updated (4421a7f4397d6a30339a26c064bbc53a51976871) the "Add dependency" section in the readme to make it more clear on how to use the latest stable release. Thanks!
